### ISSUE TITLE
Vod By Series not working

### ISSUE THREAD

**Issue by allouch89** [Shani-08/ShaniXBMCWork#208]
Hello.
The "Shahid Vod By Series" has not been working for a while.
At first i thought maybe MBC was doing some updates and should maybe just wait and try again, then i forgot about it. Today a friend of mine was trying to play some series, but it's still not working.

**Comment by Shani-08** [comment]
click download and it will show the channels etc but it wont play any video because all videos are now premium. for non geo blocked users having subscription could enter Username and pwd in the settings.
For geo blocked users, nothing is available, but work in progress. in any case they would need subscription too, unless we find a way out!

**Comment by allouch89** [comment]
aight, thanks for the information.
